# Generated by Django 2.1.5 on 2019-01-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinimoLegalSpreadsheetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet', models.FileField(upload_to='mosaico/minimo_legal_spreadsheets', verbose_name='Planilha')),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019)], verbose_name='Ano dos dados')),
                ('title_25percent', models.CharField(max_length=200, verbose_name='Título do grupo de dados - 25%')),
                ('limit_25percent', models.CharField(max_length=200, verbose_name='Texto limite do grupo de dados - 25%')),
                ('title_6percent', models.CharField(max_length=200, verbose_name='Título do grupo de dados - 6%')),
                ('limit_6percent', models.CharField(max_length=200, verbose_name='Texto limite do grupo de dados - 6%')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dados do Mínimo Legal (31%)',
                'verbose_name_plural': 'Dados do Mínimo Legal (31%)',
            },
        ),
    ]
