# Generated by Django 2.1.5 on 2019-01-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimolegalspreadsheetmodel',
            name='spreadsheet',
            field=models.FileField(upload_to='mosaico/minimo_legal_spreadsheets', verbose_name='Planilha'),
        ),
    ]
