# Generated by Django 2.1.5 on 2019-01-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimolegalspreadsheetmodel',
            name='data_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
