# Generated by Django 2.1.5 on 2019-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0002_minimolegalspreadsheetmodel_data_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimolegalspreadsheetmodel',
            name='data_extracted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
