# Generated by Django 2.1.5 on 2019-01-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0003_auto_20190115_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimolegalspreadsheetmodel',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], verbose_name='Ano dos dados'),
        ),
    ]
