from django.conf import settings

SME_ORGAO_ID = 16
ORCADO_DIFFERENCE_PERCENT_LIMIT = settings.ORCADO_DIFFERENCE_PERCENT_LIMIT  # noqa
EMPENHADO_DIFFERENCE_PERCENT_LIMIT = settings.EMPENHADO_DIFFERENCE_PERCENT_LIMIT  # noqa
