# Generated by Django 2.1.3 on 2018-12-02 18:33

from django.db import migrations, models
import from_to_handler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deflator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Ano')),
                ('index_number', models.DecimalField(decimal_places=3, help_text='Set de 2018 = 1', max_digits=4, verbose_name='Número índice')),
                ('variation_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Var %')),
            ],
            options={
                'verbose_name': 'Deflator',
                'verbose_name_plural': 'Deflator',
            },
        ),
        migrations.CreateModel(
            name='DotacaoFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexer', models.CharField(max_length=28, unique=True, verbose_name='Indexador')),
                ('grupo_code', models.IntegerField(verbose_name='Código do grupo')),
                ('grupo_desc', models.CharField(max_length=100, verbose_name='Descrição do grupo')),
                ('subgrupo_code', models.IntegerField(verbose_name='Código do subgrupo')),
                ('subgrupo_desc', models.CharField(max_length=100, verbose_name='Descrição do subgrupo')),
            ],
            options={
                'verbose_name': 'De-Para: Dotações Subgrupos Grupos',
                'verbose_name_plural': 'De-Para: Dotações Subgrupos Grupos',
            },
            bases=(models.Model, from_to_handler.models.FromTo),
        ),
        migrations.CreateModel(
            name='FonteDeRecursoFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('grupo_code', models.IntegerField(verbose_name='Código do agrupamento')),
                ('grupo_name', models.CharField(max_length=100, verbose_name='Nome do agrupamento')),
            ],
            options={
                'verbose_name': 'De-Para: Fontes de Recurso',
                'verbose_name_plural': 'De-Para: Fontes de Recurso',
            },
            bases=(models.Model, from_to_handler.models.FromTo),
        ),
        migrations.CreateModel(
            name='GNDFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnd_code', models.IntegerField(verbose_name='Código do GND')),
                ('gnd_desc', models.CharField(max_length=100, verbose_name='Descrição original do GND')),
                ('elemento_code', models.IntegerField(verbose_name='Código do Elemento de Despesa')),
                ('elemento_desc', models.CharField(max_length=100, verbose_name='Descrição do Elemento de Despesa')),
                ('new_gnd_code', models.IntegerField(verbose_name='Novo código do GND')),
                ('new_gnd_desc', models.CharField(max_length=100, verbose_name='Nova descrição do GND')),
            ],
            options={
                'verbose_name': 'De-Para: Grupos de Despesa e Elementos (GND)',
                'verbose_name_plural': 'De-Para: Grupos de Despesa e Elementos (GND)',
            },
            bases=(models.Model, from_to_handler.models.FromTo),
        ),
        migrations.CreateModel(
            name='SubelementoFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=28, verbose_name='Código')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('new_code', models.IntegerField(verbose_name='Código novo')),
                ('new_name', models.CharField(max_length=100, verbose_name='Nome novo')),
            ],
            options={
                'verbose_name': 'De-Para: Sub-elementos',
                'verbose_name_plural': 'De-Para: Sub-elementos',
            },
            bases=(models.Model, from_to_handler.models.FromTo),
        ),
    ]
