# Generated by Django 2.1.2 on 2018-11-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDeRecursoFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('group_code', models.IntegerField()),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
    ]
