# Generated by Django 2.1.4 on 2018-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deflator',
            name='year',
            field=models.DateField(unique=True, verbose_name='Ano'),
        ),
    ]
