# Generated by Django 2.1.2 on 2018-11-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubelementoFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('new_code', models.IntegerField()),
                ('new_name', models.CharField(max_length=100)),
            ],
        ),
    ]
