# Generated by Django 2.1.2 on 2018-11-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0002_subelementofromto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subelementofromto',
            name='code',
            field=models.CharField(max_length=28),
        ),
    ]
