# Generated by Django 2.1.3 on 2018-11-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0002_datamigration_adds_fromto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontederecursofromto',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Código'),
        ),
    ]
