# Generated by Django 2.1.5 on 2019-02-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0003_dotacaofromtospreadsheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotacaofromtospreadsheet',
            options={'verbose_name': 'Planilha De-Para: Dotações Subgrupos Grupos', 'verbose_name_plural': 'Planilha De-Para: Dotações Subgrupos Grupos'},
        ),
        migrations.RenameField(
            model_name='dotacaofromtospreadsheet',
            old_name='data_extracted',
            new_name='extracted',
        ),
    ]
