# Generated by Django 2.1.2 on 2018-11-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0003_auto_20181115_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotacaoFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexer', models.CharField(max_length=28)),
                ('group_code', models.IntegerField()),
                ('group_description', models.CharField(max_length=100)),
                ('subgroup_code', models.IntegerField()),
                ('subgroup_description', models.CharField(max_length=100)),
            ],
        ),
    ]
