# Generated by Django 2.1.5 on 2019-02-14 12:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0004_auto_20190213_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacaofromtospreadsheet',
            name='added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=28), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dotacaofromtospreadsheet',
            name='not_added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=28), null=True, size=None),
        ),
    ]
