# Generated by Django 2.1.2 on 2018-11-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0004_dotacaofromto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GNDFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnd_code', models.IntegerField()),
                ('gnd_description', models.CharField(max_length=100)),
                ('elemento_code', models.IntegerField()),
                ('elemento_description', models.CharField(max_length=100)),
                ('new_gnd_code', models.IntegerField()),
                ('new_gnd_description', models.CharField(max_length=100)),
            ],
        ),
    ]
