# Generated by Django 2.1.2 on 2018-11-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0005_gndfromto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deflator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('index_number', models.DecimalField(decimal_places=3, max_digits=4)),
                ('variation_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
