# Generated by Django 2.1.2 on 2018-11-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0006_deflator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deflator',
            options={'verbose_name': 'Deflator', 'verbose_name_plural': 'Deflator'},
        ),
        migrations.AlterModelOptions(
            name='dotacaofromto',
            options={'verbose_name': 'De-Para: Dotações Subgrupos Grupos', 'verbose_name_plural': 'De-Para: Dotações Subgrupos Grupos'},
        ),
        migrations.AlterModelOptions(
            name='fontederecursofromto',
            options={'verbose_name': 'De-Para: Fontes de Recurso', 'verbose_name_plural': 'De-Para: Fontes de Recurso'},
        ),
        migrations.AlterModelOptions(
            name='gndfromto',
            options={'verbose_name': 'De-Para: Grupos de Despesa e Elementos (GND)', 'verbose_name_plural': 'De-Para: Grupos de Despesa e Elementos (GND)'},
        ),
        migrations.AlterModelOptions(
            name='subelementofromto',
            options={'verbose_name': 'De-Para: Sub-elementos', 'verbose_name_plural': 'De-Para: Sub-elementos'},
        ),
    ]
