# Generated by Django 2.1.2 on 2018-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0007_auto_20181116_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deflator',
            name='index_number',
            field=models.DecimalField(decimal_places=3, help_text='Set de 2018 = 1', max_digits=4, verbose_name='Número índice'),
        ),
        migrations.AlterField(
            model_name='deflator',
            name='variation_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Var %'),
        ),
        migrations.AlterField(
            model_name='deflator',
            name='year',
            field=models.DateField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='dotacaofromto',
            name='group_code',
            field=models.IntegerField(verbose_name='Código do grupo'),
        ),
        migrations.AlterField(
            model_name='dotacaofromto',
            name='group_description',
            field=models.CharField(max_length=100, verbose_name='Descrição do grupo'),
        ),
        migrations.AlterField(
            model_name='dotacaofromto',
            name='indexer',
            field=models.CharField(max_length=28, verbose_name='Indexador'),
        ),
        migrations.AlterField(
            model_name='dotacaofromto',
            name='subgroup_code',
            field=models.IntegerField(verbose_name='Código do subgrupo'),
        ),
        migrations.AlterField(
            model_name='dotacaofromto',
            name='subgroup_description',
            field=models.CharField(max_length=100, verbose_name='Descrição do subgrupo'),
        ),
        migrations.AlterField(
            model_name='fontederecursofromto',
            name='code',
            field=models.IntegerField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='fontederecursofromto',
            name='group_code',
            field=models.IntegerField(verbose_name='Código do agrupamento'),
        ),
        migrations.AlterField(
            model_name='fontederecursofromto',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='Nome do agrupamento'),
        ),
        migrations.AlterField(
            model_name='fontederecursofromto',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='gndfromto',
            name='elemento_code',
            field=models.IntegerField(verbose_name='Código do Elemento de Despesa'),
        ),
        migrations.AlterField(
            model_name='gndfromto',
            name='elemento_description',
            field=models.CharField(max_length=100, verbose_name='Descrição do Elemento de Despesa'),
        ),
        migrations.AlterField(
            model_name='gndfromto',
            name='gnd_code',
            field=models.IntegerField(verbose_name='Código do GND'),
        ),
        migrations.AlterField(
            model_name='gndfromto',
            name='gnd_description',
            field=models.CharField(max_length=100, verbose_name='Descrição original do GND'),
        ),
        migrations.AlterField(
            model_name='gndfromto',
            name='new_gnd_code',
            field=models.IntegerField(verbose_name='Novo código do GND'),
        ),
        migrations.AlterField(
            model_name='gndfromto',
            name='new_gnd_description',
            field=models.CharField(max_length=100, verbose_name='Nova descrição do GND'),
        ),
        migrations.AlterField(
            model_name='subelementofromto',
            name='code',
            field=models.CharField(max_length=28, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subelementofromto',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='subelementofromto',
            name='new_code',
            field=models.IntegerField(verbose_name='Código novo'),
        ),
        migrations.AlterField(
            model_name='subelementofromto',
            name='new_name',
            field=models.CharField(max_length=100, verbose_name='Nome novo'),
        ),
    ]
