# Generated by Django 2.2 on 2019-04-18 20:58

from datetime import date

from django.db import migrations


def update_deflators(apps, schema_editor):
    Deflator = apps.get_model('from_to_handler', 'Deflator')
    Deflator.objects.all().delete()

    new_deflators = {
        2003: 0.434,
        2004: 0.467,
        2005: 0.493,
        2006: 0.509,
        2007: 0.532,
        2008: 0.563,
        2009: 0.587,
        2010: 0.622,
        2011: 0.662,
        2012: 0.701,
        2013: 0.742,
        2014: 0.790,
        2015: 0.874,
        2016: 0.929,
        2017: 0.957,
        2018: 0.993,
        2019: 1.000,
    }

    for year, value in new_deflators.items():
        Deflator.objects.create(year=date(year, 1, 1), index_number=value)


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0007_remove_deflator_variation_percent'),
    ]

    operations = [
        migrations.RunPython(update_deflators)
    ]
