# Generated by Django 2.1.3 on 2018-11-21 19:38

from django.core import serializers
from django.db import migrations


def load_fromto_fixture(apps, schema_editor):
    # monkey patching django serializers to use the state of the models
    # this migration is. without it, it would the state of models.py that
    # could have changed since this migration creation.
    original_apps = serializers.python.apps
    serializers.python.apps = apps

    fixture_file = './from_to_handler/migrations/data/from_to.json'
    with open(fixture_file, 'r') as fixture:
        objects = serializers.deserialize('json', fixture)
        for obj in objects:
            obj.save()

    # unpatching
    serializers.python.apps = original_apps


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0008_auto_20181116_1305'),
    ]

    operations = [
        migrations.RunPython(load_fromto_fixture),
    ]
