# Generated by Django 2.1.3 on 2018-11-27 17:54

from django.core import serializers
from django.db import migrations


def load_dotacao_fromto_fixture(apps, schema_editor):
    # monkey patching django serializers to use the state of the models
    # this migration is. without it, it would the state of models.py that
    # could have changed since this migration creation.
    original_apps = serializers.python.apps
    serializers.python.apps = apps

    DotacaoFromTo = apps.get_model('from_to_handler', 'DotacaoFromTo')
    DotacaoFromTo.objects.all().delete()

    fixture_file = ('./from_to_handler/migrations/data/'
                    'grupos_subgrupos_from_to.json')
    with open(fixture_file, 'r') as fixture:
        objects = serializers.deserialize('json', fixture)
        for obj in objects:
            obj.save()

    # unpatching
    serializers.python.apps = original_apps


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0009_datamigration_fromto_data'),
    ]

    operations = [
        migrations.RunPython(load_dotacao_fromto_fixture),
    ]
