# Generated by Django 2.1.3 on 2018-11-28 18:33

from django.db import migrations


def delete_duplicated_dotacoes_from_to(apps, schema_editor):
    DotacaoFromTo = apps.get_model('from_to_handler', 'DotacaoFromTo')

    distinct_fts = DotacaoFromTo.objects.distinct('indexer')

    for distinct_ft in distinct_fts:
        fts = DotacaoFromTo.objects.filter(indexer=distinct_ft.indexer)
        if len(fts) > 1:
            for i in range(len(fts)):
                if i == 0:
                    continue
                fts[i].delete()


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0010_datamigration_grupo_subgrupos_from_to'),
    ]

    operations = [
        migrations.RunPython(delete_duplicated_dotacoes_from_to),
    ]
