# Generated by Django 2.1.3 on 2018-11-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0011_datamigration_delete_duplicated_dotacoes_fromto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacaofromto',
            name='indexer',
            field=models.CharField(max_length=28, unique=True, verbose_name='Indexador'),
        ),
    ]
