# Generated by Django 2.1.3 on 2018-11-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('from_to_handler', '0013_auto_20181128_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotacaofromto',
            old_name='group_code',
            new_name='grupo_code',
        ),
        migrations.RenameField(
            model_name='dotacaofromto',
            old_name='group_desc',
            new_name='grupo_desc',
        ),
        migrations.RenameField(
            model_name='dotacaofromto',
            old_name='subgroup_code',
            new_name='subgrupo_code',
        ),
        migrations.RenameField(
            model_name='dotacaofromto',
            old_name='subgroup_desc',
            new_name='subgrupo_desc',
        ),
        migrations.RenameField(
            model_name='fontederecursofromto',
            old_name='group_code',
            new_name='grupo_code',
        ),
        migrations.RenameField(
            model_name='fontederecursofromto',
            old_name='group_name',
            new_name='grupo_name',
        ),
    ]
