# Generated by Django 2.1.3 on 2018-11-27 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('orcado_atualizado', models.DecimalField(decimal_places=2, max_digits=17)),
                ('empenhado_liquido', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Categoria')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Elemento')),
            ],
        ),
        migrations.CreateModel(
            name='FonteDeRecurso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gnd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoAtividade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subelemento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subfuncao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='execucao',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.FonteDeRecurso'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='gnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Gnd'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Modalidade'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Orgao'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Programa'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.ProjetoAtividade'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='subelemento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subelemento'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='subfuncao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subfuncao'),
        ),
        migrations.AlterUniqueTogether(
            name='execucao',
            unique_together={('year', 'orgao', 'projeto', 'categoria', 'gnd', 'modalidade', 'elemento', 'fonte', 'subelemento')},
        ),
    ]
