# Generated by Django 2.1.3 on 2018-11-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='execucao',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Grupo'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='subgrupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subgrupo'),
        ),
    ]
