# Generated by Django 2.1.3 on 2018-11-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0002_orgao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('orcado_atualizadao', models.DecimalField(decimal_places=2, max_digits=17)),
                ('empenhado_liquido', models.DecimalField(decimal_places=2, max_digits=17)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Categoria')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Elemento')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.FonteDeRecurso')),
                ('gnd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Gnd')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Modalidade')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Orgao')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Programa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.ProjetoAtividade')),
                ('subelemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subelemento')),
                ('subfuncao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subfuncao')),
            ],
        ),
    ]
