# Generated by Django 2.1.3 on 2018-11-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0002_auto_20181128_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='elemento',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='fontederecurso',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='gnd',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='modalidade',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='orgao',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='projetoatividade',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='subelemento',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='subfuncao',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='subgrupo',
            old_name='description',
            new_name='desc',
        ),
    ]
