# Generated by Django 2.1.3 on 2018-11-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0003_auto_20181128_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgrupo',
            old_name='_code',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='subgrupo',
            unique_together={('code', 'grupo')},
        ),
    ]
