# Generated by Django 2.1.3 on 2018-11-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0003_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoatividade',
            name='type',
            field=models.CharField(default='Atividades', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='execucao',
            name='gnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Gnd'),
        ),
    ]
