# Generated by Django 2.1.3 on 2018-11-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0004_auto_20181123_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='empenhado_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='gnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Gnd'),
        ),
    ]
