# Generated by Django 2.1.3 on 2018-11-23 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0005_auto_20181123_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execucao',
            old_name='orcado_atualizadao',
            new_name='orcado_atualizado',
        ),
        migrations.AlterField(
            model_name='execucao',
            name='gnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Gnd'),
        ),
    ]
