# Generated by Django 2.1.3 on 2018-11-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0005_auto_20181129_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='GndGealogia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='execucao',
            name='gnd_gealogia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_execution.GndGealogia'),
        ),
    ]
