# Generated by Django 2.1.3 on 2018-11-23 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0006_auto_20181123_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='gnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Gnd'),
        ),
        migrations.AlterUniqueTogether(
            name='execucao',
            unique_together={('year', 'orgao', 'projeto', 'categoria', 'gnd', 'modalidade', 'elemento', 'fonte', 'subelemento')},
        ),
    ]
