# Generated by Django 2.1.4 on 2019-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0007_auto_20181130_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='gndgealogia',
            name='slug',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
