# Generated by Django 2.1.4 on 2019-01-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0008_gndgealogia_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GndGealogia',
            new_name='GndGeologia',
        ),
        migrations.RenameField(
            model_name='execucao',
            old_name='gnd_gealogia',
            new_name='gnd_geologia',
        ),
    ]
