# Generated by Django 2.1.5 on 2019-01-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0009_auto_20190110_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimoLegal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('desc', models.CharField(max_length=250)),
                ('dotacao', models.DecimalField(decimal_places=2, max_digits=17)),
                ('despesa', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
    ]
