# Generated by Django 2.1.5 on 2019-01-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0009_auto_20190110_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimoLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('year', models.DateField()),
                ('desc', models.CharField(max_length=250)),
                ('dotacao', models.DecimalField(decimal_places=2, max_digits=17)),
                ('despesa', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='minimolegal',
            unique_together={('code', 'year')},
        ),
    ]
