# Generated by Django 2.1.5 on 2019-01-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0010_auto_20190121_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimoLegalExecucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('orcado_atualizado', models.DecimalField(decimal_places=2, max_digits=17)),
                ('empenhado_liquido', models.DecimalField(decimal_places=2, max_digits=17)),
                ('orgao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Orgao')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Programa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.ProjetoAtividade')),
                ('subfuncao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subfuncao')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='minimolegalexecucao',
            unique_together={('year', 'orgao', 'projeto', 'subfuncao', 'programa')},
        ),
    ]
