# Generated by Django 2.1.5 on 2019-01-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0010_empenho_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_execution.Execucao'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_execution.Execucao'),
        ),
    ]
