# Generated by Django 2.1.5 on 2019-01-28 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0010_auto_20190121_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimoLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('projeto_id', models.IntegerField()),
                ('projeto_desc', models.CharField(max_length=250)),
                ('orcado_atualizado', models.DecimalField(decimal_places=2, max_digits=17)),
                ('empenhado_liquido', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
        migrations.AddField(
            model_name='execucao',
            name='is_minimo_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minimolegal',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_execution.Execucao'),
        ),
        migrations.AlterUniqueTogether(
            name='minimolegal',
            unique_together={('year', 'projeto_id')},
        ),
    ]
