# Generated by Django 2.1.5 on 2019-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0011_auto_20190117_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fontederecurso',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gnd',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='initials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programa',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projetoatividade',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projetoatividade',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subelemento',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subfuncao',
            name='desc',
            field=models.TextField(),
        ),
    ]
