# Generated by Django 2.1.5 on 2019-01-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0011_auto_20190122_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimoLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('projeto_id', models.IntegerField()),
                ('projeto_desc', models.CharField(max_length=250)),
                ('orcado_atualizado', models.DecimalField(decimal_places=2, max_digits=17)),
                ('empenhado_liquido', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='minimolegal',
            unique_together={('year', 'projeto_id')},
        ),
    ]
