# Generated by Django 2.1.5 on 2019-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0011_auto_20190128_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='vl_pago_restos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='vl_orcado_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
