# Generated by Django 2.1.5 on 2019-01-31 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0012_auto_20190130_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execucao',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
