# Generated by Django 2.1.5 on 2019-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0012_auto_20190124_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='is_minimo_legal',
            field=models.BooleanField(default=False),
        ),
    ]
