# Generated by Django 2.1.5 on 2019-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0013_auto_20190131_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='execucao',
            index_together={('year', 'orgao', 'projeto', 'categoria', 'gnd', 'modalidade', 'elemento', 'fonte')},
        ),
        migrations.AlterIndexTogether(
            name='orcamento',
            index_together={('cd_ano_execucao', 'cd_projeto_atividade')},
        ),
    ]
