# Generated by Django 2.1.5 on 2019-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0014_auto_20190201_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
