# Generated by Django 2.1.5 on 2019-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0016_auto_20190227_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenhoraw',
            name='execucao_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoraw',
            name='execucao_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
