# Generated by Django 2.1.5 on 2019-04-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0017_auto_20190314_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='cd_exercicio_empresa_id',
        ),
        migrations.RemoveField(
            model_name='orcamentoraw',
            name='cd_exercicio_empresa_id',
        ),
    ]
