# Generated by Django 2.2 on 2019-05-30 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0018_auto_20190416_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='orcamento_raw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_execution.OrcamentoRaw'),
        ),
    ]
