# Generated by Django 2.2 on 2019-05-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0019_orcamento_orcamento_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoraw',
            name='execucao_id',
        ),
    ]
