# Generated by Django 2.2 on 2019-05-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0020_remove_orcamentoraw_execucao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
