# Generated by Django 2.2 on 2019-05-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0021_auto_20190530_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='dt_data_loaded',
        ),
    ]
