# Generated by Django 2.2 on 2019-05-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0023_auto_20190531_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empenhoraw',
            name='execucao_id',
        ),
    ]
