# Generated by Django 2.2 on 2019-05-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0024_remove_empenhoraw_execucao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
