# Generated by Django 2.2 on 2019-06-03 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0025_auto_20190531_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='dt_data_loaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
