# Generated by Django 2.2 on 2019-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0026_empenho_dt_data_loaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='dt_data_loaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
