# Generated by Django 2.2 on 2019-06-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0027_auto_20190603_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='orcamento_raw',
        ),
    ]
