# Generated by Django 2.2.2 on 2019-07-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0028_remove_orcamento_orcamento_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('orcado_atualizado', models.DecimalField(decimal_places=2, max_digits=17)),
                ('empenhado_liquido', models.DecimalField(decimal_places=2, max_digits=17, null=True)),
                ('is_minimo_legal', models.BooleanField(default=False)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Categoria')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Elemento')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.FonteDeRecurso')),
                ('gnd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Gnd')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Modalidade')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Orgao')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Programa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.ProjetoAtividade')),
                ('subelemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subelemento')),
                ('subfuncao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_execution.Subfuncao')),
            ],
            options={
                'unique_together': {('year', 'orgao', 'projeto', 'categoria', 'gnd', 'modalidade', 'elemento', 'fonte', 'subelemento')},
                'index_together': {('year', 'orgao', 'projeto', 'categoria', 'gnd', 'modalidade', 'elemento', 'fonte')},
            },
        ),
    ]
