# Generated by Django 2.2.2 on 2019-07-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0029_execucaotemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaotemp',
            name='is_minimo_legal',
        ),
    ]
