# Generated by Django 2.2.2 on 2019-07-04 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0030_remove_execucaotemp_is_minimo_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='execucao_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_execution.ExecucaoTemp'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='execucao_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_execution.ExecucaoTemp'),
        ),
    ]
