# Generated by Django 2.2.3 on 2019-07-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratosRawLoad',
            new_name='ContratoRaw',
        ),
    ]
