# Generated by Django 2.2.3 on 2019-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_auto_20190714_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenhosofcache',
            name='ano_exercicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
