# Generated by Django 2.2.3 on 2019-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_empenhosofcachetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCategoriaFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexer', models.CharField(max_length=28, unique=True, verbose_name='Indexador')),
                ('categoria_name', models.CharField(max_length=30, verbose_name='Nome da categoria')),
                ('categoria_desc', models.CharField(max_length=400, verbose_name='Descrição da categoria')),
            ],
            options={
                'verbose_name': 'De-Para: Contratos Categorias',
                'verbose_name_plural': 'De-Para: Contratos Categorias',
            },
        ),
    ]
