# Generated by Django 2.2.3 on 2019-08-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_execucaocontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenhosofcache',
            name='codModalidadeContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='txtDescricaoModalidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='txtObjetoContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='codModalidadeContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoModalidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='txtObjetoContrato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
