# Generated by Django 2.2.3 on 2019-08-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_auto_20190804_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empenhosofcache',
            old_name='txtDescricaoModalidade',
            new_name='txtDescricaoModalidadeContrato',
        ),
    ]
