# Generated by Django 2.2.3 on 2019-08-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_auto_20190804_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empenhosofcachetemp',
            old_name='txtDescricaoModalidade',
            new_name='txtDescricaoModalidadeContrato',
        ),
    ]
