# Generated by Django 2.2.3 on 2019-08-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_auto_20190804_0517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratoModalidade',
            new_name='ModalidadeContrato',
        ),
    ]
