# Generated by Django 2.2.3 on 2019-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_auto_20190804_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenhosofcache',
            name='datEmpenho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='nomEmpresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='numCpfCnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtCategoriaEconomica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoElemento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoFonteRecurso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoFuncao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoItemDespesa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoOrgao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoPrograma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoProjetoAtividade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoSubElemento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoSubFuncao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtDescricaoUnidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtGrupoDespesa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtModalidadeAplicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcache',
            name='txtRazaoSocial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='datEmpenho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='nomEmpresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='numCpfCnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtCategoriaEconomica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoElemento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoFonteRecurso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoFuncao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoItemDespesa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoOrgao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoPrograma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoProjetoAtividade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoSubElemento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoSubFuncao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoUnidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtGrupoDespesa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtModalidadeAplicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empenhosofcachetemp',
            name='txtRazaoSocial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.TextField(),
        ),
    ]
