# Generated by Django 2.2.3 on 2019-08-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_auto_20190804_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratoCategoria',
            new_name='CategoriaContrato',
        ),
    ]
