# Generated by Django 2.2.3 on 2019-08-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_auto_20190804_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaocontrato',
            name='empenho_indexer',
            field=models.CharField(max_length=28, unique=True),
        ),
    ]
