# Generated by Django 2.2.3 on 2019-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_auto_20190807_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratoraw',
            old_name='anoexercicio',
            new_name='anoExercicio',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='codcontrato',
            new_name='codContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='codempresa',
            new_name='codEmpresaContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='codmodalidade',
            new_name='codModalidadeContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='codorgao',
            new_name='codOrgaoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='codprocesso',
            new_name='codProcessoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='codtipocontratacao',
            new_name='codTipoContratacaoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='datassinaturacontrato',
            new_name='datAssinaturaContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='datpublicacaocontrato',
            new_name='datPublicacaoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='datvigencia',
            new_name='datVigenciaContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='data_extracao',
            new_name='dataExtracaoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='dt_data_loaded',
            new_name='dtDataLoadedContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='numoriginalcontrato',
            new_name='numOriginalContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='txtdescricaomodalidade',
            new_name='txtDescricaoModalidadeContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='txtdescricaoorgao',
            new_name='txtDescricaoOrgaoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='txtobjetocontrato',
            new_name='txtObjetoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='txtrazaosocial',
            new_name='txtRazaoSocialContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='txttipocontratacao',
            new_name='txtTipoContratacaoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valaditamentos',
            new_name='valAditamentosContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valanulacao',
            new_name='valAnulacaoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valanuladoempenho',
            new_name='valAnuladoEmpenhoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valempenhadoliquido',
            new_name='valEmpenhadoLiquidoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valpago',
            new_name='valPagoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valprincipal',
            new_name='valPrincipalContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valreajustes',
            new_name='valReajustesContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valtotalempenhado',
            new_name='valTotalEmpenhadoContrato',
        ),
        migrations.RenameField(
            model_name='contratoraw',
            old_name='valliquidado',
            new_name='valliquidadoContrato',
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='anoExercicio',
            field=models.IntegerField(blank=True, db_column='anoexercicio', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='codContrato',
            field=models.IntegerField(blank=True, db_column='codcontrato', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='codEmpresaContrato',
            field=models.IntegerField(blank=True, db_column='codempresa', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='codModalidadeContrato',
            field=models.IntegerField(blank=True, db_column='codmodalidade', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='codOrgaoContrato',
            field=models.IntegerField(blank=True, db_column='codorgao', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='codProcessoContrato',
            field=models.BigIntegerField(blank=True, db_column='codprocesso', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='codTipoContratacaoContrato',
            field=models.IntegerField(blank=True, db_column='codtipocontratacao', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='datAssinaturaContrato',
            field=models.DateField(blank=True, db_column='datassinaturacontrato', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='datPublicacaoContrato',
            field=models.DateField(blank=True, db_column='datpublicacaocontrato', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='datVigenciaContrato',
            field=models.DateField(blank=True, db_column='datvigencia', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='dataExtracaoContrato',
            field=models.DateField(blank=True, db_column='data_extracao', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='dtDataLoadedContrato',
            field=models.CharField(blank=True, db_column='dt_data_loaded', max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='numOriginalContrato',
            field=models.TextField(blank=True, db_column='numoriginalcontrato', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='txtDescricaoModalidadeContrato',
            field=models.TextField(blank=True, db_column='txtdescricaomodalidade', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='txtDescricaoOrgaoContrato',
            field=models.TextField(blank=True, db_column='txtdescricaoorgao', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='txtObjetoContrato',
            field=models.TextField(blank=True, db_column='txtobjetocontrato', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='txtRazaoSocialContrato',
            field=models.TextField(blank=True, db_column='txtrazaosocial', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='txtTipoContratacaoContrato',
            field=models.TextField(blank=True, db_column='txttipocontratacao', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valAditamentosContrato',
            field=models.FloatField(blank=True, db_column='valaditamentos', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valAnulacaoContrato',
            field=models.FloatField(blank=True, db_column='valanulacao', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valAnuladoEmpenhoContrato',
            field=models.FloatField(blank=True, db_column='valanuladoempenho', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valEmpenhadoLiquidoContrato',
            field=models.FloatField(blank=True, db_column='valempenhadoliquido', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valPagoContrato',
            field=models.FloatField(blank=True, db_column='valpago', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valPrincipalContrato',
            field=models.FloatField(blank=True, db_column='valprincipal', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valReajustesContrato',
            field=models.FloatField(blank=True, db_column='valreajustes', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valTotalEmpenhadoContrato',
            field=models.FloatField(blank=True, db_column='valtotalempenhado', null=True),
        ),
        migrations.AlterField(
            model_name='contratoraw',
            name='valliquidadoContrato',
            field=models.FloatField(blank=True, db_column='valliquidado', null=True),
        ),
    ]
