# Generated by Django 2.2.3 on 2019-08-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_auto_20190807_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacontrato',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
