# Generated by Django 2.2.3 on 2019-08-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_auto_20190808_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratoraw',
            old_name='anoExercicio',
            new_name='anoExercicioContrato',
        ),
        migrations.RenameField(
            model_name='empenhosofcache',
            old_name='anoExercicio',
            new_name='anoExercicioContrato',
        ),
        migrations.RenameField(
            model_name='empenhosofcachetemp',
            old_name='anoExercicio',
            new_name='anoExercicioContrato',
        ),
    ]
