# Generated by Django 2.2.3 on 2019-08-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_auto_20190808_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenhosofcache',
            name='codEmpresaContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='codOrgaoContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='codProcessoContrato',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='codTipoContratacaoContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='datAssinaturaContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='datPublicacaoContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='datVigenciaContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='dataExtracaoContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='dtDataLoadedContrato',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='numOriginalContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='txtDescricaoOrgaoContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='txtRazaoSocialContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='txtTipoContratacaoContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valAditamentosContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valAnulacaoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valAnuladoEmpenhoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valEmpenhadoLiquidoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valPagoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valPrincipalContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valReajustesContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valTotalEmpenhadoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcache',
            name='valliquidadoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='codEmpresaContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='codOrgaoContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='codProcessoContrato',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='codTipoContratacaoContrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='datAssinaturaContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='datPublicacaoContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='datVigenciaContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='dataExtracaoContrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='dtDataLoadedContrato',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='numOriginalContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='txtDescricaoOrgaoContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='txtRazaoSocialContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='txtTipoContratacaoContrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valAditamentosContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valAnulacaoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valAnuladoEmpenhoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valEmpenhadoLiquidoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valPagoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valPrincipalContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valReajustesContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valTotalEmpenhadoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empenhosofcachetemp',
            name='valliquidadoContrato',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
