# Generated by Django 2.2.3 on 2019-08-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_categoriacontrato_slug'),
        ('contratos', '0025_auto_20190808_1635'),
    ]

    operations = [
    ]
