# Generated by Django 2.2.3 on 2019-08-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_merge_20190812_1934'),
        ('contratos', '0026_auto_20190812_1718'),
    ]

    operations = [
    ]
