# Generated by Django 2.2.3 on 2019-08-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0027_merge_20190812_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaocontrato',
            name='empenho_indexer',
            field=models.CharField(max_length=28),
        ),
    ]
