# Generated by Django 2.2.3 on 2019-09-03 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0028_auto_20190820_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaocontrato',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
