# Generated by Django 2.2.3 on 2019-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0029_execucaocontrato_dt_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacontrato',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categoriacontrato',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
