# Generated by Django 2.2.3 on 2019-10-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0031_auto_20190909_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empenhosofcache',
            options={'verbose_name_plural': 'Empenhos SOF Cache'},
        ),
        migrations.AlterModelOptions(
            name='empenhosofcachetemp',
            options={'verbose_name_plural': 'Empenhos SOF Cache (Temp table)'},
        ),
        migrations.AlterModelOptions(
            name='empenhosoffailedapirequest',
            options={'verbose_name_plural': 'Empenhos SOF APi Failed Requests'},
        ),
    ]
