# Generated by Django 2.2.6 on 2019-11-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0033_auto_20191017_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaocontrato',
            name='empenho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.EmpenhoSOFCache'),
        ),
    ]
