# Generated by Django 2.2.6 on 2019-11-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0034_execucaocontrato_empenho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaocontrato',
            name='empenho',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.EmpenhoSOFCache'),
        ),
    ]
