# Generated by Django 2.2.7 on 2019-12-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0035_auto_20191113_1726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empenhosofcache',
            unique_together={('codContrato', 'anoExercicioContrato', 'anoEmpenho', 'codCategoria', 'codElemento', 'codEmpenho', 'codEmpresa', 'codFonteRecurso', 'codFuncao', 'codGrupo', 'codItemDespesa', 'codModalidade', 'codOrgao', 'codProcesso', 'codPrograma', 'codProjetoAtividade', 'codSubElemento', 'codSubFuncao', 'codUnidade', 'datEmpenho', 'mesEmpenho', 'numCpfCnpj', 'numReserva', 'valAnuladoEmpenho', 'valEmpenhadoLiquido', 'valLiquidado', 'valPagoExercicio', 'valPagoRestos', 'valTotalEmpenhado')},
        ),
        migrations.AlterUniqueTogether(
            name='empenhosofcachetemp',
            unique_together={('codContrato', 'anoExercicioContrato', 'anoEmpenho', 'codCategoria', 'codElemento', 'codEmpenho', 'codEmpresa', 'codFonteRecurso', 'codFuncao', 'codGrupo', 'codItemDespesa', 'codModalidade', 'codOrgao', 'codProcesso', 'codPrograma', 'codProjetoAtividade', 'codSubElemento', 'codSubFuncao', 'codUnidade', 'datEmpenho', 'mesEmpenho', 'numCpfCnpj', 'numReserva', 'valAnuladoEmpenho', 'valEmpenhadoLiquido', 'valLiquidado', 'valPagoExercicio', 'valPagoRestos', 'valTotalEmpenhado')},
        ),
    ]
