# Generated by Django 2.2.6 on 2019-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0003_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistritoZonaFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coddist', models.IntegerField(unique=True)),
                ('zona', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaTipoEscolaFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoesc', models.CharField(max_length=10)),
                ('desctipoesc', models.CharField(max_length=100)),
                ('etapa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PtrfFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesc', models.IntegerField(unique=True)),
                ('vlrepasse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeRecursosFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesc', models.IntegerField(unique=True)),
                ('grupo', models.CharField(max_length=30)),
                ('subgrupo', models.CharField(blank=True, max_length=30, null=True)),
                ('valor', models.IntegerField()),
                ('label', models.CharField(max_length=20)),
            ],
        ),
    ]
