# Generated by Django 2.2.6 on 2019-11-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0004_distritozonafromto_etapatipoescolafromto_ptrffromto_unidaderecursosfromto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptrffromto',
            name='vlrepasse',
            field=models.FloatField(),
        ),
    ]
