# Generated by Django 2.2.6 on 2019-11-11 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0005_auto_20191111_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distritozonafromtospreadsheet',
            name='added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='distritozonafromtospreadsheet',
            name='not_added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='etapatipoescolafromtospreadsheet',
            name='added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='etapatipoescolafromtospreadsheet',
            name='not_added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ptrffromtospreadsheet',
            name='added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ptrffromtospreadsheet',
            name='not_added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromtospreadsheet',
            name='added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromtospreadsheet',
            name='not_added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), editable=False, null=True, size=None),
        ),
    ]
