# Generated by Django 2.2.6 on 2019-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0006_auto_20191111_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidaderecursosfromto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
