# Generated by Django 2.2.6 on 2019-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0007_auto_20191111_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidaderecursosfromto',
            name='codesc',
            field=models.IntegerField(),
        ),
    ]
