# Generated by Django 2.2.6 on 2019-11-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0008_auto_20191111_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distritozonafromto',
            options={'verbose_name': 'De-Para: Distrito-Zona', 'verbose_name_plural': 'De-Para: Distrito-Zona'},
        ),
        migrations.AlterModelOptions(
            name='etapatipoescolafromto',
            options={'verbose_name': 'De-Para: Etapa-Tipo Escola', 'verbose_name_plural': 'De-Para: Etapa-Tipo Escola'},
        ),
        migrations.AlterModelOptions(
            name='ptrffromto',
            options={'verbose_name': 'De-Para: PTRF', 'verbose_name_plural': 'De-Para: PTRF'},
        ),
        migrations.AlterModelOptions(
            name='unidaderecursosfromto',
            options={'verbose_name': 'De-Para: Unidade-Recursos', 'verbose_name_plural': 'De-Para: Unidade-Recursos'},
        ),
        migrations.AddField(
            model_name='ptrffromtospreadsheet',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='Ano dos dados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidaderecursosfromtospreadsheet',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='Ano dos dados'),
            preserve_default=False,
        ),
    ]
