# Generated by Django 2.2.6 on 2019-11-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0009_auto_20191115_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptrffromto',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='Ano dos dados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidaderecursosfromto',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='Ano dos dados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ptrffromto',
            name='codesc',
            field=models.IntegerField(),
        ),
    ]
