# Generated by Django 2.2.6 on 2019-11-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0010_auto_20191116_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapatipoescolafromto',
            name='tipoesc',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
