# Generated by Django 2.2.6 on 2019-11-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0013_dre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Escola',
        ),
    ]
