# Generated by Django 2.2.6 on 2019-11-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0015_distrito_tipoescola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesc', models.IntegerField(unique=True)),
                ('nomesc', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('rede', models.CharField(choices=[('DIR', 'Rede direta SME'), ('CON', 'Rede parceira contratada')], max_length=3)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_vagas', models.IntegerField()),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regionalizacao.Distrito')),
                ('dre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regionalizacao.Dre')),
                ('tipoesc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regionalizacao.TipoEscola')),
            ],
        ),
    ]
