# Generated by Django 2.2.7 on 2019-11-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0017_auto_20191125_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='codesc',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
