# Generated by Django 2.2.7 on 2019-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0018_auto_20191125_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptrffromto',
            name='codesc',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromto',
            name='codesc',
            field=models.CharField(max_length=7),
        ),
    ]
