# Generated by Django 2.2.7 on 2019-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0020_distrito_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoescola',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipoescola',
            name='etapa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
