# Generated by Django 2.2.7 on 2019-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0021_auto_20191128_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='zona',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
