# Generated by Django 2.2.7 on 2019-11-28 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0023_auto_20191128_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptrffromtospreadsheet',
            name='added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ptrffromtospreadsheet',
            name='updated_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromtospreadsheet',
            name='added_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromtospreadsheet',
            name='updated_fromtos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None),
        ),
    ]
