# Generated by Django 2.2.7 on 2019-11-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0024_auto_20191128_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptrffromto',
            name='year',
            field=models.IntegerField(verbose_name='Ano dos dados'),
        ),
        migrations.AlterField(
            model_name='ptrffromtospreadsheet',
            name='year',
            field=models.IntegerField(verbose_name='Ano dos dados'),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromto',
            name='year',
            field=models.IntegerField(verbose_name='Ano dos dados'),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromtospreadsheet',
            name='year',
            field=models.IntegerField(verbose_name='Ano dos dados'),
        ),
    ]
