# Generated by Django 2.2.7 on 2019-11-29 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0025_auto_20191129_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('ptrf', models.FloatField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regionalizacao.Escola')),
            ],
        ),
    ]
