# Generated by Django 2.2.7 on 2019-11-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0027_grupo_recurso_subgrupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
