# Generated by Django 2.2.7 on 2019-11-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0029_recurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecucaoEscola',
        ),
    ]
