# Generated by Django 2.2.7 on 2019-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0030_delete_execucaoescola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019),
        ),
    ]
