# Generated by Django 2.2.7 on 2019-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0031_escola_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='ptrf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
