# Generated by Django 2.2.7 on 2019-12-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0032_escola_ptrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='codesc',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='escola',
            unique_together={('codesc', 'year')},
        ),
    ]
