# Generated by Django 2.2.7 on 2019-12-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0034_auto_20191202_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='codesc',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='escola',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='escola',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='dre',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='nomesc',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='ptrf',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='rede',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='tipoesc',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='total_vagas',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='year',
        ),
        migrations.CreateModel(
            name='EscolaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2019)),
                ('nomesc', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('rede', models.CharField(choices=[('DIR', 'Rede direta SME'), ('CON', 'Rede parceira contratada')], max_length=3)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_vagas', models.IntegerField()),
                ('ptrf', models.FloatField(blank=True, null=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regionalizacao.Distrito')),
                ('dre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regionalizacao.Dre')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='regionalizacao.Escola')),
                ('tipoesc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regionalizacao.TipoEscola')),
            ],
            options={
                'unique_together': {('escola', 'year')},
            },
        ),
    ]
