# Generated by Django 2.2.7 on 2019-12-02 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0035_auto_20191202_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escolainfo',
            name='ptrf',
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2019)),
                ('ptrf', models.FloatField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='regionalizacao.Escola')),
            ],
            options={
                'unique_together': {('escola', 'year')},
            },
        ),
    ]
