# Generated by Django 2.2.7 on 2019-12-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0036_auto_20191202_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
