# Generated by Django 2.2.7 on 2019-12-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0040_auto_20191203_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidaderecursosfromto',
            name='grupo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromto',
            name='label',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromto',
            name='subgrupo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
