# Generated by Django 2.2.7 on 2019-12-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0041_auto_20191203_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolainfo',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
