# Generated by Django 2.2.7 on 2019-12-04 14:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0042_auto_20191203_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolainfo',
            name='recursos',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
