# Generated by Django 2.2.7 on 2019-12-04 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0043_escolainfo_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolainfo',
            name='budget_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escolainfo',
            name='recursos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
