# Generated by Django 2.2.7 on 2019-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0044_auto_20191204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgrupo',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
