# Generated by Django 2.2.7 on 2019-12-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0045_auto_20191205_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapatipoescolafromto',
            name='etapa',
            field=models.CharField(max_length=100),
        ),
    ]
