# Generated by Django 2.2.7 on 2019-12-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0046_auto_20191206_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoescola',
            name='etapa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
