# Generated by Django 2.2.7 on 2019-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0048_auto_20191213_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distritozonafromto',
            name='zona',
            field=models.CharField(max_length=50),
        ),
    ]
