# Generated by Django 2.2.7 on 2019-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0048_auto_20191213_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptrffromtospreadsheet',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unidaderecursosfromtospreadsheet',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
    ]
