# Generated by Django 2.2.7 on 2020-01-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0049_auto_20191220_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='escolainfo',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
