# Generated by Django 3.1.1 on 2020-09-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0051_updatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dre',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
