# Generated by Django 2.2.7 on 2020-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0052_auto_20200930_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolainfo',
            name='qtd_matriculas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escolainfo',
            name='qtd_servidores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
