# Generated by Django 3.1.1 on 2020-10-05 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0052_auto_20200930_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeValoresVerbaFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano dos dados')),
                ('codigo_escola', models.CharField(blank=True, max_length=6)),
                ('valor_mensal', models.FloatField(blank=True, null=True)),
                ('verba_locacao', models.FloatField(blank=True, null=True)),
                ('valor_mensal_iptu', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'De-Para: Unidade-Valores-Verba',
                'verbose_name_plural': 'De-Para: Unidade-Valores-Verba',
            },
        ),
        migrations.CreateModel(
            name='UnidadeValoresVerbaFromToSpreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet', models.FileField(upload_to='regionalizacao/fromto_spreadsheets', verbose_name='Planilha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted', models.BooleanField(default=False, editable=False)),
                ('added_fromtos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None)),
                ('updated_fromtos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), editable=False, null=True, size=None)),
                ('year', models.IntegerField(verbose_name='Ano dos dados')),
            ],
            options={
                'verbose_name': 'Planilha Unidade-Valores-Verba',
                'verbose_name_plural': 'Planilhas Unidade-Valores-Verba',
            },
        ),
    ]
