# Generated by Django 3.1.1 on 2020-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0053_unidadevaloresverbafromto_unidadevaloresverbafromtospreadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadevaloresverbafromto',
            name='codigo_escola',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
