# Generated by Django 3.1.1 on 2020-10-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0055_auto_20201005_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='valor_mensal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='valor_mensal_iptu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='verba_locacao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
