# Generated by Django 3.1.1 on 2020-10-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionalizacao', '0053_auto_20201002_1503'),
        ('regionalizacao', '0056_auto_20201005_1859'),
    ]

    operations = [
    ]
